name: Changelog

on:
  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v2

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@upgrade_to_1.15.2
        with:
          token: ${{ GITHUB_TOKEN }}
          exclude_labels: ci

      - name: Check for changes
        run: |
          if [[ `git status --porcelain` ]]; then
            echo ::set-env name=changes::1
          fi

      - name: Create Pull Request
        if: env.changes == 1
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ GITHUB_TOKEN }}
          commit-message: "Updated CHANGELOG.md"
          title: 'Update CHANGELOG'
          body: |
            Updated CHANGELOG.md
          branch: changelog
